<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>CENOP</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
  <link rel="stylesheet"href="<?php echo $this->url->get('css/jquery-ui.min.css')?>"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css">
  <link rel="stylesheet"href="<?php echo $this->url->get('css/estilos.css')?>"/>
  <link rel="stylesheet"href="<?php echo $this->url->get('css/fullcalendar.css')?>"/>
  <link rel="stylesheet"href="<?php echo $this->url->get('css/fullcalendar.print.css')?>"/>
  <link rel="stylesheet" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
</head>
<body>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/es.js"></script>
  <script src="<?php echo $this->url->get('js/modernizr.custom.js')?>"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/js/bootstrap-datetimepicker.min.js"></script>
  <script src="<?php echo $this->url->get('js/bootbox.min.js')?>"></script>
  <script src="<?php echo $this->url->get('js/jquery-ui.custom.min.js')?>"></script>
  <script src="<?php echo $this->url->get('js/fullcalendar.js')?>"></script>
  <script src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/alasql/0.4.5/alasql.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.12.12/xlsx.core.min.js"></script>
  <div class="container" style="width:100%;padding-top: 35px;">
    <?php echo $this->getContent(); ?>
  </div>

  <div class="barra-menu">

  </div>
  <div id="MenuPrincipal" class="no-imprimir">
    <i class="material-icons icono-menu">&#xE5D2;</i>
    <div class="sobre-menu-principal"></div>
    <div class="menu-principal">
      <div class="header-menu-principal">
        <div>
          <img id="avatarprincipal" src="<?php echo $this->url->get('img/logo.jpg')?>" />
          <br />
          <b>Nombre:&ensp;</b><span id="username"><?php echo $this->session->get('auth')['nombre']; ?></span>
        </div>
      </div>
      <div class="body-menu-principal">
        <div class="item-menu not-paci not-ort not-emp">
          <i class="material-icons">&#xE862;</i>
          <span><?php echo $this->tag->linkTo("ortopedista/index", "Técnico Ortopedista") ?></span>
        </div>
        <div class="item-menu not-paci not-ort not-emp">
          <i class="material-icons ">&#xE862;</i>
          <span><?php echo $this->tag->linkTo("paciente/index", "Paciente") ?></span>
        </div>
        <div class="item-menu not-paci not-ort not-emp">
          <i class="material-icons">&#xE862;</i>
          <span><?php echo $this->tag->linkTo("empresa/index", "Cliente") ?></span>
        </div>
        <div class="item-menu">
          <i class="material-icons">&#xE8D3;</i>
          <span><?php echo $this->tag->linkTo("agenda/new", "Agenda Citas") ?></span>
        </div>
        <div class="item-menu not-paci">
          <i class="material-icons">&#xE8D3;</i>
          <span><?php echo $this->tag->linkTo("ordenproduccion/index", "Orden Producción") ?></span>
        </div>
        <div class="item-menu not-paci not-emp not-ort">
          <i class="material-icons">&#xE8D3;</i>
          <span><?php echo $this->tag->linkTo("detalleingreso/index", "Ingreso Materia Prima") ?></span>
        </div>
        <div class="item-menu not-paci not-emp">
          <i class="material-icons">&#xE8D3;</i>
          <span><?php echo $this->tag->linkTo("detalleactividad/index", "Actividades del usuario") ?></span>
        </div>
        <div class="item-menu not-paci not-emp">
          <i class="material-icons">&#xE8D3;</i>
          <span><?php echo $this->tag->linkTo("valoracion/index", "Valoración integral") ?></span>
        </div>
        <div class="footer-menu-principal">
          <div><i class="material-icons" title="Editar información">&#xE88E;</i></div>
          <div><a class="material-icons" href="/session/end">&#xE8AC;</a></div>
          <!--<div><i class="material-icons">&#xE869;</i></div>-->
        </div>
      </div>
    </body>
    </html>
    <script type="text/javascript">
    $(".icono-menu").click(function () {

      $(".sobre-menu-principal").fadeIn();
      $(".menu-principal").animate({
        left: "0"
      }, 500);
    });

    $(".sobre-menu-principal").click(function () {

      $(".sobre-menu-principal").fadeOut();
      $(".menu-principal").animate({
        left: "-1000px"
      }, 500);
    });
    $(".not-paci").css('display', 'flex');
    $(".not-emp").css('display', 'flex');
    $(".not-ort").css('display', 'flex');
    var tipoUsuario = '<?php echo $this->session->get("auth")["tipoUsuario"]; ?>';
    if (tipoUsuario == 3) {
      $(".not-paci").css('display', 'none');
    }else if (tipoUsuario == 2) {
      $(".not-emp").css('display', 'none');
    }else if (tipoUsuario == 1) {
      $(".not-ort").css('display', 'none');
    }
    console.log("<?php echo $this->session->get('auth')['nombre']; ?>");

    </script>
